project:
  type: website

website:
  title: "Duncan J. Mayer"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/duncan-mayer
      - icon: linkedin
        href: https://linkedin.com/in/duncan-mayer
format:
  html:
    theme: lux
    css: styles.css
    mainfont: times

editor: visual

